### ISSUE TITLE
Cargo.lock missing

### ISSUE THREAD

**Issue by pcboy** [HarlemSquirrel/tzf-rb#50]
Hello,

It seems you are missing a Cargo.lock in the repo. I believe it should be in the ext/tzf folder.  
This cause me issues while trying to build the the gem with Nix, as it requires the Cargo.lock for proper reproducibility.  
Is it possible to add it?

**Comment by HarlemSquirrel** [comment]
The lock file is at the top level. What commands are you running to install or build this?

**Comment by pcboy** [comment]
I sadly couldn't find back the package.nix I did at that time. I remember trying to use the Cargo.lock at the root of the repo without success (hash mismatch issues.)

So I tried again, and somehow this time I made it work. But only if i have internet. By just adding in my nix shell:

```nix
      buildInputs = with pkgs; [
            rustPlatform.bindgenHook
          ];
```

But in a pure nix sandbox (no internet), it fails because it's trying to access crates.io. It isn't supposed to since I'm doing:

```nix
              cargoDeps = pkgs.rustPlatform.fetchCargoVendor {
                src = stdenv.mkDerivation {
                  inherit (pkgs.buildRubyGem { inherit (attrs) gemName version source; })
                    name
                    src
                    unpackPhase
                    nativeBuildInputs
                    ;
                  installPhase = ''
                    cp -R ext/tzf $out
                    cp Cargo.lock $out
                  '';
                };
                hash = "sha256-ranajlIEPMP9bjCnHFZPipx4F/rNzUHBKWYJ+YHe0u0=";
              };
```

Which is supposed to handle this.  

But I finally found what was missing ultimately:

```nix
              preInstall = ''
                export CARGO_HOME="$PWD/../.cargo/"
              '';
```

The .cargo contains a file `config.toml` with:

```toml
[source.vendored-sources]
directory = "/build/cargo-deps-vendor"
[source.crates-io]
replace-with = "vendored-sources"
    [target."x86_64-unknown-linux-gnu"]
"linker" = "/nix/store/dc6bahp3f5af2rxz3pal9m3kp4vx4rpy-gcc-wrapper-14.2.1.20250322/bin/cc"
"rustflags" = [ "-C", "target-feature=-crt-static" ]
```

So that solves it. I will likely add this package configuration to nixpkgs so it's easier for others to use.

Thank you.
